spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: true
  thymeleaf:
    mode: HTML
  application:
    name: backend-web
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./db/backend;DB_CLOSE_DELAY=-1
    username: backend
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /db-console
      settings:
        web-allow-others: true
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

application:
  email: hanoilacnhaucoinhumat@gmail.com
#  email: project.devskill@gmail.com
  path:
    new-product-file: /home/hoaronal/project/products_new.xlsx
    file-download: /home/hoaronal/project/products.xlsx
    # file-download: /Users/hoadoan/Desktop/products.xlsx
    chrome-driver: /home/hoaronal/project/chromedriver
    # chrome-driver: /Users/hoadoan/Desktop/chrome_driver/chromedriver
